GENERICRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('enroll.urls'))
]

enroll/urls.py
from django.urls import path
from .views import StuCreView, StuUpdView, StuDelView, StudentListView

urlpatterns = [
    path('', StuCreView.as_view(template_name ='enroll/add.html'), name='add'),
    path('show/', StudentListView.as_view(template_name='enroll/show.html'), name='show'),
    path('update/<int:pk>/', StuUpdView.as_view(template_name='enroll/update.html'), name='update'),
    path('delete/<int:pk>/', StuDelView.as_view(template_name='enroll/addshow.html'), name='delete')
]

enroll/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=30)
    password = models.CharField(max_length=15)

enroll/forms.py
from django import forms
from .models import Student

class StudentFM(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'email':forms.EmailInput(attrs={'class':'form-control'}),
            'password':forms.PasswordInput(attrs={'class':'form-control'})
        }

enroll/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import StudentFM
from .models import Student
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.

# def addshow(request):
#     if request.method == 'POST':
#         fm = StudentFM(request.POST)
#         if fm.is_valid():
#             fm.save()
#             return HttpResponseRedirect('/')
#     else:
#         fm = StudentFM()
#     return render(request, 'enroll/addshow.html', {'form':fm, 'data':Student.objects.all()})

class StuCreView(CreateView):
    CreateView.form_class = StudentFM
    success_url = '/'

class StudentListView(ListView):
    model = Student


class StuDelView(DeleteView):
    model = Student
    success_url = '/show/'

class StuUpdView(UpdateView):
    model = Student
    form_class = StudentFM
    success_url = '/show/'

# def delete(request, id):
#     if request.method == 'POST':
#         Student.objects.get(pk=id).delete()
#         return HttpResponseRedirect('/')

# def update(request, id):
#     pi = Student.objects.get(pk=id)
#     if request.method == 'POST':
#         fm = StudentFM(request.POST, instance=pi)
#         fm.save()
#         return HttpResponseRedirect('/')
#     else:
#         fm = StudentFM(instance=pi)
#     return render(request, 'enroll/update.html', {'form':fm})

enroll/templates/enroll/add.html
{% extends 'enroll/base.html' %}
{% block content %}
    <div class="row justify-content-evenly">
        <div class="col-sm-8">
            <h4 class="alert-secondary text-center">Add New Student/User</h4>
            <form method="POST"> {% csrf_token %}
                {{form.as_p}}
                <input type="submit" class="btn btn-success" value='Add'>
                <a href="{% url 'show' %}" class="btn btn-secondary">Show Data</a>
            </form>
        </div>
    </div>
{% endblock content %}

enroll/templates/enroll/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <h3 class="text-center alert alert-danger">Function Based ModelForm CRUD Project</h3>
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

enroll/templates/enroll/show.html
{% extends 'enroll/base.html' %}
{% load static %}
{% block content %}
    <div class="row justify-content-evenly">
        <div class="col-md-8">
            <h4 class="alert-info text-center">See Student/User Info</h4>
            {% if student_list %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">NAME</th>
                        <th scope="col">EMAIL</th>
                        <th scope="col">PASSWORD</th>
                        <th scope="col">ACTION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dt in student_list %}
                        <tr>
                            <th scope='row'>{{dt.id}}</th>
                            <td>{{dt.name}}</td>
                            <td>{{dt.email}}</td>
                            <td>{{dt.password}}</td>
                            <td>
                                <a href="{% url 'update' dt.id %}" class="btn btn-sm btn-warning">Edit</a>
                                <form action="{% url 'delete' dt.id %}" method='POST' class="d-inline"> {% csrf_token %}
                                    <input type="submit" value='Delete' class="btn btn-sm btn-danger">
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <hr><hr>
            <a href="{% url 'add' %}" class="btn btn-primary">Add New Data</a>
            {% else %}
                <h4 class="text-center alert alert-warning">No Student/User Data Found</h4>
            {% endif %}
        </div>
    </div>
{% endblock content %}

enroll/templates/enroll/update.html
{% extends 'enroll/base.html' %}
{% block content %}
    <div class="row justify-content-evenly">
        <div class="col-md-8">
            <h4 class="text-center alert-primary">Update Student/User Info</h4>
            <form method="POST"> {% csrf_token %}
                {{form.as_p}}
                <input type="submit" vlaue='Update' class="btn btn-success">
                <a href="{% url 'show' %}" class="btn btn-info">Back to Home</a>
            </form>
        </div>
    </div>
{% endblock content %}